### PR TITLE
Vm options for executable added to configuration

### PR DESCRIPTION
**Pull request by hraada**
I have added vm options for executable to come closer to configuration options of javafx-maven-plugin. It's needed for example when --add-opens needs to be used.

### CODE REVIEW

**Comment by abhinayagarwal** [comment]
Hi @hraada,

Do you still want to take this PR forward. If yes, please add proper documentation for this change.

**Comment by hraada** [comment]
Hi, I already use my fork, but I would like to finish this - I will add the documentation.

**Comment by hraada** [comment]
I have added documentation and I have also refactored the naming a little bit to make it clear, what it is actually doing.

**Comment by abhinayagarwal** [comment]
Now that documentation is added, I can see this PR adds JVM args to `JavaExec` task. The JavaExec is derived from the application plugin whose `run{..}` can be overloaded to provide the `jvmArgs`. As a general rule, we do not wish to duplicate the parameters that is already provided by the application plugin. 

In `javafx-maven-plugin` , it made sense to add the `jvmArgs` because the execution is handled by the plugin via `javafx:run` goal.

Having said that, this change can provide the user with an easy way to overload `jvmArgs` inside `javafx{..}`without the need to introduce a `run{..}`.

Although I think this change is not required, I would request @tiainen and @jperedadnr to share their thoughts.

**Comment by tiainen** [comment]
I agree that this doesn't add much value. Configuring these options via the `run` configuration block is more straightforward. The only reason I can think of for adding this option, is that the arguments could be added to the java command in a very specific location, in case order matters. 

However, I do note that the docs should mention somewhere that the exec task is basically running the exec task of the application plugin. And that all configuration can be done in the usual way by using the run block.

**Pull request closed without merging**
